name: Deploy Cloud Function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v3
        with:
          name: fitness-api
          runtime: python311
          region: australia-southeast1
          source_dir: Functions
          entry_point: fitness_api
          project_id: fitness-tracker-poc-492000
          ingress_settings: ALLOW_ALL
        
